/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as SitemapPagesXmlRouteImport } from './routes/sitemap-pages.xml'
import { Route as SitemapLegalXmlRouteImport } from './routes/sitemap-legal.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminFinancesRouteImport } from './routes/admin.finances'

const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesXmlRoute = SitemapPagesXmlRouteImport.update({
  id: '/sitemap-pages/xml',
  path: '/sitemap-pages/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapLegalXmlRoute = SitemapLegalXmlRouteImport.update({
  id: '/sitemap-legal/xml',
  path: '/sitemap-legal/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap-legal/xml': typeof SitemapLegalXmlRoute
  '/sitemap-pages/xml': typeof SitemapPagesXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap-legal/xml': typeof SitemapLegalXmlRoute
  '/sitemap-pages/xml': typeof SitemapPagesXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap-legal/xml': typeof SitemapLegalXmlRoute
  '/sitemap-pages/xml': typeof SitemapPagesXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/admin/finances'
    | '/admin/leads'
    | '/admin/projects'
    | '/auth/callback'
    | '/robots/txt'
    | '/sitemap-legal/xml'
    | '/sitemap-pages/xml'
    | '/sitemap/xml'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/admin/finances'
    | '/admin/leads'
    | '/admin/projects'
    | '/auth/callback'
    | '/robots/txt'
    | '/sitemap-legal/xml'
    | '/sitemap-pages/xml'
    | '/sitemap/xml'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/admin/finances'
    | '/admin/leads'
    | '/admin/projects'
    | '/auth/callback'
    | '/robots/txt'
    | '/sitemap-legal/xml'
    | '/sitemap-pages/xml'
    | '/sitemap/xml'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapLegalXmlRoute: typeof SitemapLegalXmlRoute
  SitemapPagesXmlRoute: typeof SitemapPagesXmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages/xml': {
      id: '/sitemap-pages/xml'
      path: '/sitemap-pages/xml'
      fullPath: '/sitemap-pages/xml'
      preLoaderRoute: typeof SitemapPagesXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-legal/xml': {
      id: '/sitemap-legal/xml'
      path: '/sitemap-legal/xml'
      fullPath: '/sitemap-legal/xml'
      preLoaderRoute: typeof SitemapLegalXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinancesRoute: AdminFinancesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapLegalXmlRoute: SitemapLegalXmlRoute,
  SitemapPagesXmlRoute: SitemapPagesXmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
